DATABASE_URI = ''

FINNHUB_API_KEY = ''
FAST_API_ORIGIN = ''

SEC_REQUEST_HEADER_USER_AGENT = ''

TDA_ACCOUNT_NUMBER = ''
TDA_API_KEY = ''
TDA_REDIRECT_URI = ''
TDA_TOKEN_PATH = ''

WEBDRIVER_PATH = ''
